import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

const generatePDF = (interview, user) => {
  const doc = new jsPDF();

  // ======================================
  // Title
  // ======================================

  doc.setFontSize(22);
  doc.setTextColor(37, 99, 235);
  doc.text("AI MOCK INTERVIEW REPORT", 105, 20, {
    align: "center",
  });

  doc.setDrawColor(37, 99, 235);
  doc.setLineWidth(0.5);
  doc.line(20, 28, 190, 28);

  // ======================================
  // Candidate Information
  // ======================================

  doc.setFontSize(16);
  doc.setTextColor(0, 0, 0);
  doc.text("Candidate Information", 20, 40);

  doc.setFontSize(12);

  doc.text(`Name : ${user.fullName}`, 20, 50);

  doc.text(`Email : ${user.email}`, 20, 58);

  doc.text(`Category : ${interview.category}`, 20, 66);

  doc.text(`Difficulty : ${interview.difficulty}`, 20, 74);

  doc.text(
    `Interview Date : ${new Date(
      interview.createdAt
    ).toLocaleDateString()}`,
    20,
    82
  );

  doc.text(
    `Overall Score : ${interview.overallScore}/100`,
    20,
    90
  );

  // ======================================
  // Overall Feedback
  // ======================================

  doc.setFontSize(16);
  doc.setTextColor(37, 99, 235);

  doc.text("Overall Feedback", 20, 105);

  doc.setFontSize(11);
  doc.setTextColor(0);

  doc.text(
    interview.overallFeedback || "No Feedback Available",
    20,
    114,
    {
      maxWidth: 170,
    }
  );

  // ======================================
  // Question Wise Analysis
  // ======================================

  autoTable(doc, {
    startY: 135,

    head: [
      [
        "Question",
        "Score",
        "Feedback",
      ],
    ],

    body: interview.questions.map((question) => [
      question.question,
      `${question.score}/10`,
      question.feedback,
    ]),

    styles: {
      fontSize: 9,
      valign: "middle",
    },

    headStyles: {
      fillColor: [37, 99, 235],
      textColor: [255, 255, 255],
    },

    columnStyles: {
      0: {
        cellWidth: 80,
      },
      1: {
        cellWidth: 20,
      },
      2: {
        cellWidth: 80,
      },
    },
  });

  // ======================================
  // Footer
  // ======================================

  const pageHeight = doc.internal.pageSize.height;

  doc.setFontSize(10);

  doc.setTextColor(120);

  doc.text(
    "Generated by AI Mock Interview Platform",
    105,
    pageHeight - 10,
    {
      align: "center",
    }
  );

  // ======================================
  // Download PDF
  // ======================================

  doc.save(`AI_Report_${user.fullName}.pdf`);
};

export default generatePDF;